cdm in progress

diff --git a/bin/cvm b/bin/cvm
--- a/bin/cvm
+++ b/bin/cvm
@@ -2,6 +2,7 @@
 
 CVM_PREFIX=${CVM_PREFIX-/usr/local}
 VERSIONS_DIR=$CVM_PREFIX/n/versions
+CORTEX_MIRROR=${CORTEX_MIRROR-http://registry.npmjs.org}
 
 #
 # Log <type> <msg>
@@ -17,6 +18,19 @@ abort() {
   printf "\n  \033[31mError: $@\033[0m\n\n" && exit 1
 }
 
+#
+# Ensure we have curl or wget support.
+#
+GET=
+
+# wget support (Added --no-check-certificate for Github downloads)
+command -v wget > /dev/null && GET="wget --no-check-certificate -q -O-"
+command -v curl > /dev/null && GET="curl -# -L"
+test -z "$GET" && abort "curl or wget required"
+
+#
+# Display help information
+#
 display_help() {
   cat <<-EOF
 
@@ -59,21 +73,6 @@ check_current_version() {
 }
 
 #
-# Download a resource `$1` into directory `$2`
-#
-download() {
-  wget $1
-}
-
-#
-# Generate the tarbal url by version `$1`
-#
-get_tarball_url() {
-  v="$1"
-  tarbal_url="http://registry.npmjs.org/cortex/-/cortex-$v.tgz"
-}
-
-#
 # List installed versions.
 #
 list_versions_installed() {
@@ -83,17 +82,123 @@ list_versions_installed() {
   done
 }
 
+#
+# Download a resource `$1` into directory `$2`
+#
+download() {
+  wget $1
+}
 
+#
+# Check if the HEAD response of <url> is 200.
+#
+is_ok() {
+  curl -Is $1 | head -n 1 | grep 200 > /dev/null
+}
 
+#
+# Generate the tarbal url by version `$1`
+#
+tarball_url() {
+  local v="$1"
+  echo "$CORTEX_MIRROR/cortex/-/cortex-$v.tgz"
+}
 
+#
+# Activate <version>
+#
+activate() {
+  local version=$1
+  check_current_version
+  if test "$version" != "$active"; then
+    local dir=$VERSIONS_DIR/$version
+    echo $active > $VERSIONS_DIR/.prev
+    cp -fR $dir/bin $dir/lib $dir/include $dir/share $N_PREFIX
+  fi
+}
 
+#
+# Install cortex
+#
+install_cortex() {
+  # Remove leading `'v'`
+  local version=${1#v}
 
+  local dots=`echo $version | sed 's/[^.]*//g'`
+  if test ${#dots} -eq 1; then
+    version=`$GET 2> /dev/null $CORTEX_MIRROR \
+      | egrep -o '[0-9]+\.[0-9]+\.[0-9]+' \
+      | egrep -v '^0\.[0-7]\.' \
+      | egrep -v '^0\.8\.[0-5]$' \
+      | sort -u -k 1,1n -k 2,2n -k 3,3n -t . \
+      | egrep ^$version \
+      | tail -n1`
 
+    test $version || abort "invalid version ${1#v}"
+  fi
 
+  local dir=$VERSIONS_DIR/$version
+  local url=$(tarball_url $version)
 
+  # If already installed, activate it.
+  if test -d $dir; then
+    if [[ ! -e $dir/n.lock ]] ; then
+      activate $version
+      exit
+    fi
+  fi
 
+  echo
+  log install v$version
 
+  is_ok $url || abort "invalid version $version"
 
+  log mkdir $dir
+  mkdir -p $dir
+  if [ $? -ne 0 ] ; then
+    abort "sudo required"
+  else
+    touch $dir/n.lock
+  fi
+
+  cd $dir
+
+  log fetch $url
+  curl -L# $url | tar -zx --strip 1
+  erase_line
+  rm -f $dir/n.lock
+
+  activate $version
+  log installed $(node --version)
+  echo
+}
+
+#
+# Activate <version>
+#
+activate() {
+  local version=$1
+  check_current_version
+  if test "$version" != "$active"; then
+    local dir=$VERSIONS_DIR/$version
+    echo $active > $VERSIONS_DIR/.prev
+    cp -fR $dir/bin $dir/lib $dir/include $dir/share $N_PREFIX
+  fi
+}
+
+#
+# 
+#
+cvm_strip_path() {
+
+}
+
+#
+# 
+#
+cvm_prepend_path() {
+
+}
 
 
 # Credit
