supports to display all remote versions; fixes #4

diff --git a/bin/cvm b/bin/cvm
--- a/bin/cvm
+++ b/bin/cvm
@@ -96,7 +96,7 @@ resolve_version() {
   else
     log "resolving" "'$v' from remote server"
     version=`cvmutil version $version`
-    test_version "$version" || abort "invalid version $v, or no internet connection."
+    test_version "$version" || abort "invalid range $v, or no internet connection."
   fi
 }
 
@@ -128,33 +128,24 @@ list_versions_installed() {
 }
 
 
-# display_remote_versions() {
-#   check_current_version
-#   local response=""
-#   response=`$GET 2> /dev/null $CVM_MIRROR`
-#   response=${response//'/\'}
-#   response=${response/"/\"}
-#   local versions=(`node -e "Object.keys(JSON.parse('$response').versions).join(' ')"`)
-#     # | egrep -o '[0-9]+\.[0-9]+\.[0-9]+' \
-#     # | egrep -v '^0\.[0-7]\.' \
-#     # | egrep -v '^0\.8\.[0-5]$' \
-#     # | sort -u -k 1,1n -k 2,2n -k 3,3n -t . \
-#     # | awk '{ print "  " $1 }'`
+display_remote_versions() {
+  check_current_version
+  local versions=`cvmutil versions`
+  versions=("$versions")
 
-#   echo
-#   for v in $versions; do
-#     if test "$active" = "$v"; then
-#       printf "  \033[36mο\033[0m $v \033[0m\n"
-#     else
-#       if test -d $VERSIONS_DIR/$v; then
-#         printf "    $v \033[0m\n"
-#       else
-#         printf "    \033[90m$v\033[0m\n"
-#       fi
-#     fi
-#   done
-#   echo
-# }
+  for v in $versions; do
+    if test "$active" = "$v"; then
+      printf "  \033[36mο\033[0m $v \033[0m\n"
+    else
+      if test -d $VERSIONS_DIR/$v; then
+        printf "    $v \033[0m\n"
+      else
+        printf "    \033[90m$v\033[0m\n"
+      fi
+    fi
+  done
+  echo
+}
 
 #
 # Display installed versions with <selected>
@@ -391,7 +382,7 @@ else
         ;;
 
       "ls" | "list" )
-        echo "comming..."
+        display_remote_versions
         ;;
 
       "use" )
