bin in progress

diff --git a/bin/cvm b/bin/cvm
--- a/bin/cvm
+++ b/bin/cvm
@@ -1,7 +1,122 @@
+#!/usr/bin/env bash
+
+CVM_PREFIX=${CVM_PREFIX-/usr/local}
+VERSIONS_DIR=$CVM_PREFIX/n/versions
+
 #
 # Log <type> <msg>
 #
-
 log() {
   printf "  \033[36m%10s\033[0m : \033[90m%s\033[0m\n" $1 $2
 }
+
+#
+# Exit with the given <msg ...>
+#
+abort() {
+  printf "\n  \033[31mError: $@\033[0m\n\n" && exit 1
+}
+
+display_help() {
+  cat <<-EOF
+
+  Usage: n [COMMAND] [args]
+
+  Commands:
+    cvm                       Output versions installed
+    cvm latest                Install the latest cortex
+    cvm <version>             Install cortex <version>
+    cvm use <version>         Switch to the given version
+    cvm rm <version ...>      Remove the given version(s)
+    cvm list, cvm ls          Output the versions of cortex available
+
+    -V, --version             Output current version of n
+    -h, --help                Display help information
+
+EOF
+  exit 0
+}
+
+#
+# Display sorted versions directories paths.
+#
+versions_paths() {
+  ls -d $VERSIONS_DIR/* \
+    | egrep "/[0-9]+\.[0-9]+\.[0-9]+$" \
+    | sort -k 1,1n -k 2,2n -k 3,3n -t .
+}
+
+
+#
+# Check for installed version, and populate $active
+#
+check_current_version() {
+  command -v cortex &> /dev/null
+  if test $? -eq 0; then
+    active=`node --version`
+    active=${active#v}
+  fi
+}
+
+#
+# Download a resource `$1` into directory `$2`
+#
+download() {
+  wget $1
+}
+
+#
+# Generate the tarbal url by version `$1`
+#
+get_tarball_url() {
+  v="$1"
+  tarbal_url="http://registry.npmjs.org/cortex/-/cortex-$v.tgz"
+}
+
+#
+# List installed versions.
+#
+list_versions_installed() {
+  for dir in `versions_paths`; do
+    local version=${dir##*/}
+    echo $version
+  done
+}
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+# Credit
+# A lot of bash functions from visionmedia/n
+
+# (The MIT License)
+# Copyright (c) 2014 TJ Holowaychuk <tj@vision-media.ca>
+
+# Permission is hereby granted, free of charge, to any person obtaining
+# a copy of this software and associated documentation files (the
+# 'Software'), to deal in the Software without restriction, including
+# without limitation the rights to use, copy, modify, merge, publish,
+# distribute, sublicense, and/or sell copies of the Software, and to
+# permit persons to whom the Software is furnished to do so, subject to
+# the following conditions:
+
+# The above copyright notice and this permission notice shall be
+# included in all copies or substantial portions of the Software.
+
+# THE SOFTWARE IS PROVIDED 'AS IS', WITHOUT WARRANTY OF ANY KIND,
+# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
+# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
+# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
+# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
+# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
+# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
